### PR TITLE
Add prettier

### PR DESCRIPTION
**Pull request by Shinigami92**
This adds Prettier to the project with a configuration that is aligned in a way that it approximates the current format as much as possible

However, there are 
- .yml and .yaml files
- different indentations in .json files (2 vs 4)
- no support for non-spaces imports
- no TS declarations trailing comma support 😢 

The [eslint-plugin-modules-newline](https://github.com/gmsorrow/eslint-plugin-modules-newline) is not maintained anymore
I assume there is somewhere another rule, maybe by eslint-plugin-unicorn, but I didn't find it on the fly with a 1min quick search
The eslint-plugin-modules-newline has a conflict with prettier, not sure if eslint-plugin-prettier could help here, but anyway 😸 

In addition, we could add a `prettier --check` to the GitHub CI like here https://github.com/faker-js/faker/blob/872c855d4a288e85ff7486aff7e3dfcfedea8c62/.github/workflows/ci.yml#L169-L170, but that's up to you

### CODE REVIEW

**Comment by Shinigami92** [comment]
Ah! https://github.com/import-js/eslint-plugin-import can do the `modules-newline` stuff.
There are several rules that can work together:
- https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/exports-last.md
- https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/group-exports.md
- https://github.com/import-js/eslint-plugin-import/blob/HEAD/docs/rules/first.md
- https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/newline-after-import.md

Should I configure this in this PR? Or should I do a follow-up PR later on?

**Review by sgohlke — APPROVED** [review]
Thank you for your MR, this looks good and helpful for reading the code.

**Comment by sgohlke** [comment]
> Ah! https://github.com/import-js/eslint-plugin-import can do the `modules-newline` stuff. There are several rules that can work together:
> 
> * https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/exports-last.md
> * https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/group-exports.md
> * https://github.com/import-js/eslint-plugin-import/blob/HEAD/docs/rules/first.md
> * https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/newline-after-import.md
> 
> Should I configure this in this PR? Or should I do a follow-up PR later on?

I think I will merge this MR first so the prettier changes are applied. I'll handle the import/export formatting in a separate MR. As we use eslint-plugin-simple-import-sort with eslint-plugin-import in newer projects and it sorts the imports a bit different I can handle this in one MR. 

We try to keep the projects consistent, so I need to add the prettier changes to other libraries and also apply the import/export sorting.

> In addition, we could add a `prettier --check` to the GitHub CI like here https://github.com/faker-js/faker/blob/872c855d4a288e85ff7486aff7e3dfcfedea8c62/.github/workflows/ci.yml#L169-L170, but that's up to you

That is a good point. I'll prepare it in the MRs and after it is available in all libs I can add it to our central CI workflow.

**Comment by Shinigami92** [comment]
> We try to keep the projects consistent, so I need to add the prettier changes to other libraries [...].

I just started with this project as I assumed that it is the "base"
So I can do PRs for the other project as well (I assume it is "only" the `graphql-server`)

I planned to enhance the project further with other changes like e.g. using `tsup` for the build process and e.g. switching the test-suite to vitest, so the tests can run faster.

**Comment by sgohlke** [comment]
> > We try to keep the projects consistent, so I need to add the prettier changes to other libraries [...].
> 
> I just started with this project as I assumed that it is the "base" So I can do PRs for the other project as well (I assume it is "only" the `graphql-server`)

I appreciate the thought, as I'm doing updates anyway I can handle this.
 
> I planned to enhance the project further with other changes like e.g. using `tsup` for the build process and e.g. switching the test-suite to `vitest`, so the tests can run faster.

It would be nice if you open an issue with "enhancement" label so we can discuss the changes before you create an MR. Might be bad if you create an MR and we decide we don't want to apply a specific change. Most of the NodeJS libraries are focused for backend use and not every change might make sense for them.

**Comment by Shinigami92** [comment]
Yes, I will create Issues.
Sometimes PRs just are good demonstrations, but if they don't get accepted, they can be trashed away without any struggle 🙂

**Comment by sgohlke** [comment]
> Yes, I will create Issues. Sometimes PRs just are good demonstrations, but if they don't get accepted, they can be trashed away without any struggle 🙂

I agree on that point, thought it might be easier to try out/showcase the changes in https://github.com/dreamit-de/graphql-prom-metrics project as it is smaller than https://github.com/dreamit-de/graphql-server .

**Pull request merged**
